FROM python:3.13.3-slim-buster
WORKDIR /app
COPY requirements_ui.txt .
RUN pip install --no-cache-dir -r requirements_ui.txt
COPY main.py .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]